# From https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml 
on:
    push:
      branches: main
    workflow_run:
      workflows: ["Copy daily"]
      types:
        - completed

name: Assemble hourly and daily data sets
  
  # you need these permissions to publish to GitHub pages
  # permissions: 
  #     contents: write
  #     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Set up R dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Update Hourly data set
        run: Rscript R/cleaning/clean_hourly.R

      - name: Update Daily data set
        run: Rscript R/cleaning/clean_daily.R

      - name: Commit data sets
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GHA Bot"
          git pull
          git add data/hourly/hourly.rds
          git commit -m "Update hourly data set"
          git add data/daily/daily.rds
          git commit -m "Update daily data set"
          git push

