name: Copy daily

on:
  schedule:
    - cron:  '00 18 * * *'
  workflow_dispatch:

jobs:
  copy-daily:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Get daily
          id: remote-file-daily
          run: curl -s "https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2024/72565003017.csv" > data/daily/raw/2024.csv
        - name: Get hourly
          id: remote-file-hourly
          run: curl -s "https://www.ncei.noaa.gov/data/global-hourly/access/2024/72565003017.csv" > data/hourly/raw/2024.csv
        - name: update date
          run: echo `date '+%Y-%m-%dT%T'` > now.txt
        - name: Update changed files
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GHA Bot"
            git add data/daily/raw/2024.csv
            git add now.txt
            git pull --ff-only
            git commit -m "Update year 2024 daily"
            git push
