name: Copy daily

on:
  schedule:
    - cron:  '00 1 * * *'

jobs:
  copy-daily:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Get remote file
          id: remote-file
          run: curl -s "https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2023/72565003017.csv" > data/daily/raw/2023.csv
        - name: update date
          run: echo `date '+%Y-%m-%dT%T'` > now.txt
        - name: Update changed files
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GHA Bot"
            git add data/daily/raw/2023.csv
            git add now.txt
            git pull --ff-only
            git commit -m "Update year 2023 daily"
            git push